# Note, FFTW version 3 must be installed to compile this code.
#
# It is assumed that the include file fftw3.h FFTW's static library files are in standard locations that GCC knows about.
# If this is not the case then you need to add the flag -I/wherever/fftw.h/is/located/at to CXXFLAGS
# and add the path of libfftw3.la to the environment variable LIBRARY_PATH.

CXXFLAGS = -Wall -std=c++11 -O3 -ffast-math
LDFLAGS = -lfftw3

CROSSPROB_OBJECTS = build/crossprob.o build/one_sided_noncrossing_probability.o build/two_sided_noncrossing_probability.o build/fftw_wrappers.o build/fftwconvolver.o build/string_utils.o build/read_boundaries_file.o

CROSSPROB_MC_OBJECTS = build/crossprob_mc.o build/string_utils.o build/read_boundaries_file.o build/tinymt64.o

all: crossprob crossprob_mc

crossprob: build bin $(CROSSPROB_OBJECTS)
	$(CXX) $(CROSSPROB_OBJECTS) $(LDFLAGS) -o bin/$@ 

crossprob_mc: build bin $(CROSSPROB_MC_OBJECTS)
	$(CXX) $(CROSSPROB_MC_OBJECTS) $(LDFLAGS) -o bin/$@ 

clean:
	rm -rf build
	rm -rf bin

test:
	python tests/test_crossprob.py

swig:
	swig -c++ -python  -o python_extension/crossprob_swig_wrap.cc src/crossprob.i

depend:
	makedepend src/*.cc python_extension/*.cc

build/%.o: src/%.cc
	$(CXX) -c -o $@ $< $(CXXFLAGS)

build:
	mkdir build

bin:
	mkdir bin

# The following dependencies are generated by running "make depend"
# DO NOT DELETE

src/crossprob.o: src/one_sided_noncrossing_probability.hh
src/crossprob.o: src/two_sided_noncrossing_probability.hh
src/crossprob.o: src/read_boundaries_file.hh src/string_utils.hh
src/crossprob_mc.o: src/string_utils.hh src/read_boundaries_file.hh
src/crossprob_mc.o: src/tinymt64.h /usr/include/stdint.h
src/crossprob_mc.o: /usr/include/sys/_types/_int8_t.h
src/crossprob_mc.o: /usr/include/sys/_types/_int16_t.h
src/crossprob_mc.o: /usr/include/sys/_types/_int32_t.h
src/crossprob_mc.o: /usr/include/sys/_types/_int64_t.h
src/crossprob_mc.o: /usr/include/_types/_uint8_t.h
src/crossprob_mc.o: /usr/include/_types/_uint16_t.h
src/crossprob_mc.o: /usr/include/_types/_uint32_t.h
src/crossprob_mc.o: /usr/include/_types/_uint64_t.h /usr/include/sys/_types.h
src/crossprob_mc.o: /usr/include/sys/cdefs.h
src/crossprob_mc.o: /usr/include/sys/_symbol_aliasing.h
src/crossprob_mc.o: /usr/include/sys/_posix_availability.h
src/crossprob_mc.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
src/crossprob_mc.o: /usr/include/sys/_pthread/_pthread_types.h
src/crossprob_mc.o: /usr/include/sys/_types/_intptr_t.h
src/crossprob_mc.o: /usr/include/sys/_types/_uintptr_t.h
src/crossprob_mc.o: /usr/include/_types/_intmax_t.h
src/crossprob_mc.o: /usr/include/_types/_uintmax_t.h /usr/include/inttypes.h
src/crossprob_mc.o: /usr/include/Availability.h
src/crossprob_mc.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
src/crossprob_mc.o: /usr/include/sys/_types/_wchar_t.h
src/fftw_wrappers.o: src/fftw_wrappers.hh src/aligned_mem.hh
src/fftwconvolver.o: src/fftw_wrappers.hh src/fftwconvolver.hh
src/fftwconvolver.o: src/aligned_mem.hh
src/one_sided_noncrossing_probability.o: src/one_sided_noncrossing_probability.hh
src/read_boundaries_file.o: src/read_boundaries_file.hh src/string_utils.hh
src/string_utils.o: src/string_utils.hh
src/tinymt64.o: src/tinymt64.h /usr/include/stdint.h
src/tinymt64.o: /usr/include/sys/_types/_int8_t.h
src/tinymt64.o: /usr/include/sys/_types/_int16_t.h
src/tinymt64.o: /usr/include/sys/_types/_int32_t.h
src/tinymt64.o: /usr/include/sys/_types/_int64_t.h
src/tinymt64.o: /usr/include/_types/_uint8_t.h
src/tinymt64.o: /usr/include/_types/_uint16_t.h
src/tinymt64.o: /usr/include/_types/_uint32_t.h
src/tinymt64.o: /usr/include/_types/_uint64_t.h /usr/include/sys/_types.h
src/tinymt64.o: /usr/include/sys/cdefs.h /usr/include/sys/_symbol_aliasing.h
src/tinymt64.o: /usr/include/sys/_posix_availability.h
src/tinymt64.o: /usr/include/machine/_types.h /usr/include/i386/_types.h
src/tinymt64.o: /usr/include/sys/_pthread/_pthread_types.h
src/tinymt64.o: /usr/include/sys/_types/_intptr_t.h
src/tinymt64.o: /usr/include/sys/_types/_uintptr_t.h
src/tinymt64.o: /usr/include/_types/_intmax_t.h
src/tinymt64.o: /usr/include/_types/_uintmax_t.h /usr/include/inttypes.h
src/tinymt64.o: /usr/include/Availability.h
src/tinymt64.o: /usr/include/AvailabilityInternal.h /usr/include/_types.h
src/tinymt64.o: /usr/include/sys/_types/_wchar_t.h
src/two_sided_noncrossing_probability.o: src/fftwconvolver.hh
src/two_sided_noncrossing_probability.o: src/aligned_mem.hh
